name: Daily push

on:
  push:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    environment: checkin_environment

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check in
        run: |
          python ./bot.py